# Generated by Django 5.1.1 on 2024-12-08 20:42

import livraison.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='qr_path',
            field=models.ImageField(blank=True, null=True, upload_to=livraison.models.generate_qr_code_path, verbose_name='QR Code Path'),
        ),
    ]
