# Generated by Django 5.1.1 on 2024-12-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0002_livraison_qr_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='commande',
        ),
        migrations.AlterField(
            model_name='livraison',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
