# Generated by Django 5.1.1 on 2024-12-09 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0004_commande_comments_commande_is_ordered_and_more'),
        ('livraison', '0003_remove_livraison_commande_alter_livraison_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='commande',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='commande.commande', verbose_name='Commande'),
            preserve_default=False,
        ),
    ]
