# Generated by Django 5.1.1 on 2024-12-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0004_livraison_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='incremental_id',
            field=models.IntegerField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='qr_path',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Code Path'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='tracking_number',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='Tracking Number'),
        ),
    ]
