# Generated by Django 4.2 on 2024-11-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=100)),
                ('description_produit', models.TextField()),
                ('image_produit', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('categorie_produit', models.CharField(max_length=50)),
                ('quantite_produit', models.PositiveIntegerField(default=0)),
                ('prix_produit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fournisseur_produit', models.CharField(max_length=100)),
            ],
        ),
    ]
