# Generated by Django 4.2 on 2024-11-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateField(auto_now=True)),
                ('date_livraison', models.DateField()),
                ('methode_livraison', models.CharField(default='Express', max_length=50)),
                ('adresse_livraison', models.CharField(default='Tunis', max_length=50)),
                ('quantite_commande', models.IntegerField()),
            ],
        ),
    ]
