# Generated by Django 5.1.1 on 2024-12-03 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0003_initial'),
        ('produit', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commande',
            name='adresse_livraison',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_livraison',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='methode_livraison',
            field=models.CharField(blank=True, default='Express', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='produit_commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='produit.produit'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='quantite_commande',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='commande',
            name='user_commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL),
        ),
    ]
